---
version: '2.1'

services:
  geoserver:
    image: camptocamp/geoserver:2.17
    volumes:
      - /tmp/geoserver-data:/mnt/geoserver_datadir

  print:
    image: mapfish_print_tester
    user: ${USER_ID}
    volumes:
      - ./examples/src/test/resources/examples:/usr/local/tomcat/webapps/ROOT/print-apps
      - ./core:/opt/core
    ports:
      - 8080:8080
    environment:
      PRINT_YAML_MAX_ALIASES: 200
      LOG_LEVEL: DEBUG
      JASPER_LOG_LEVEL: DEBUG
      JAVA_OPTS: -Dsun.net.inetaddr.ttl=30 -javaagent:/usr/local/tomcat/webapps/ROOT/WEB-INF/lib/jmx_prometheus_javaagent-0.18.0.jar=9110:/opt/core/jmx-exporter.yaml

  tests:
    image: mapfish_print_builder
    user: ${USER_ID}
    command: tail --follow /dev/null
    volumes:
      - ./examples/src/test/resources/examples:/src/examples/src/test/resources/examples
    environment:
      PRINT_YAML_MAX_ALIASES: 200
      GRADLE_USER_HOME: /home/gradle/.gradle
